services:
  db:
    image: postgres:16.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: demo
      POSTGRES_USER: demo
      POSTGRES_DB: demo
    command: '-c log_statement=all'
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
